### PR TITLE
Added Twitch Support

### PR DESCRIPTION
**Pull request by witnessmenow**
- Added support for connecting to Twitch Chat
- Added basic example for twitch chat
- Re-organized examples
- Updated version number to 0.2.0

Thanks for the library!

### CODE REVIEW

**Comment by fredimachado** [comment]
Hi Brian!

Thanks a lot for the PR. I have some suggestions though:

Although I love the Twitch chat example, I don't think we should have a `connectTwitch` function, as currently it's only adding support to PASS (which I guess the library should have supported it from the beginning). The point is, we shouldn't have an implementation specific for Twitch chat (only the example).

I recommend updating the PR to something like this:

```c
boolean IRCClient::connect(String nickname, String user, String password) {
  if (!connected()) {
    int result = client->connect(this->host, this->port);
    if (result == 1) {
      this->nickname = nickname;
      if (password != "") {
        sendIRC("PASS " + password);
      }
      sendIRC("NICK " + nickname);
      sendIRC("USER " + user + " 8 * :Arduino IRC Client");
      this->isConnected = true;
      return true;
    }
    return false;
  }
  return true;
}

boolean IRCClient::connect(String nickname, String user) {
  return connect(nickname, user, "");
}
```

Thanks a lot!

**Comment by witnessmenow** [comment]
Hey,

This is exactly what I thought originally! I was working on this on a
stream last night and did exactly the change you sent back, (well other
than I had one method and made pass default to blank, your way is better)

But it it wasn't working and I eventually figured why! The twitch
implementation is non standard

Standard implementation:

sendIRC("HELLO");
sendIRC("NICK " + nickname);
sendIRC("USER " + user + " 8 * :Arduino IRC Client");

Twitch implementation:

sendIRC("PASS " + password);
sendIRC("NICK " + nickname);
sendIRC("JOIN " + user);

There is no "hello", "user" has changed to "join" and the "Arduino IRC"
part is removed.

If you have any other suggestions on how to re-organize it I'd be happy to
hear them

Brian

**Comment by fredimachado** [comment]
Hi Brian,

I guess it should be fine to send USER to twitch chat, since all IRC clients send it anyway.
The HELLO is not really needed, as it's not a requirement in RFC 1459 or 2812.
And about JOIN, you could manually join the channel after connecting to the server.

It should work just fine. Could you please test it since I moved places and I don't have any boards available to test? (My boards are in another country, hehehe)

Oh, I've just followed you on Twitch. Looking forward to watching you there. I'm fredimachadotv there.

Cheers!

**Comment by fredimachado** [comment]
I've tried connecting to twitch chat using my .NET core irc client library and it works fine (it sends USER as well). I had to send the JOIN command after connecting though. I guess that was your problem.

(I have automated builds, even for PRs: https://travis-ci.org/fredimachado/ArduinoIRC/builds/412874418)

**Comment by witnessmenow** [comment]
Cool! I'll tidy it up later and test it out and update the PR.

Brian

**Comment by witnessmenow** [comment]
Hey,

I tested what you suggested and it worked fine, so updated the PR.

- I made password an optional variable of connect function (it should work the exact same as what you had suggested, but we only need one connect definition). I have tested that basicESP8266.ino compiles, but I have no actually tested with an IRC server.
- I moved out the "join" to the sketch level in the twitch example

**Comment by fredimachado** [comment]
Awesome! Thanks a lot Brian!

**Pull request merged**
